# Generated by Django 3.2.15 on 2023-01-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date/Time')),
                ('chars', models.IntegerField(default=1, verbose_name='Chars')),
                ('lang', models.CharField(max_length=5, verbose_name='Language')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
