# Generated by Django 3.2.15 on 2023-01-02 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gtranslator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GTransCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=100, verbose_name='Hash')),
                ('source', models.TextField(verbose_name='Source')),
            ],
        ),
        migrations.AddField(
            model_name='usage',
            name='cached',
            field=models.BooleanField(default=False, verbose_name='Cached'),
        ),
        migrations.CreateModel(
            name='GTransCacheLang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=5, verbose_name='Language')),
                ('target', models.TextField(verbose_name='Target')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtranslator.gtranscache')),
            ],
        ),
    ]
