# Generated by Django 3.2.15 on 2023-01-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtranslator', '0002_auto_20230102_1935'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GTransCacheLang',
        ),
        migrations.RemoveField(
            model_name='gtranscache',
            name='id',
        ),
        migrations.AddField(
            model_name='gtranscache',
            name='lang',
            field=models.CharField(default='en', max_length=5, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='gtranscache',
            name='hash',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Hash'),
        ),
        migrations.AlterField(
            model_name='gtranscache',
            name='source',
            field=models.TextField(default='', verbose_name='Source'),
        ),
    ]
