# Generated by Django 3.2.15 on 2023-01-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtranslator', '0003_auto_20230104_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gtranscache',
            name='source',
            field=models.TextField(default='', verbose_name='Text'),
        ),
    ]
