# Generated by Django 3.2.12 on 2022-08-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_newsshot_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsshot',
            name='user_agent',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
