# Generated by Django 4.1.7 on 2023-05-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_newsshot_user_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsshot',
            name='customer_type',
            field=models.CharField(default='C', max_length=1),
        ),
    ]
