# Generated by Django 3.2.9 on 2022-03-31 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomersBehaviourData',
            fields=[
                ('id_customer', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='DailySalesData',
            fields=[
                ('date_add', models.DateField(primary_key=True, serialize=False)),
                ('products', models.IntegerField(blank=True, null=True)),
                ('orders', models.IntegerField(blank=True, null=True)),
                ('GBP_cost', models.FloatField(blank=True, null=True)),
                ('GBP_products', models.FloatField(blank=True, null=True)),
                ('GBP_shipping', models.FloatField(blank=True, null=True)),
                ('GBP_paid', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyCustomersData',
            fields=[
                ('month', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyTotalCustomersData',
            fields=[
                ('month', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductsData',
            fields=[
                ('id_product', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
