# Generated by Django 3.2.9 on 2022-03-31 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MissGelProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color_number', models.CharField(max_length=50)),
                ('packing', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('gellifique_name', models.CharField(max_length=50)),
                ('gellifique_old_names', models.CharField(max_length=500)),
                ('gellifique_ean13', models.CharField(max_length=13)),
                ('gellifique_old_ean13', models.CharField(max_length=500)),
            ],
            options={
                'unique_together': {('name', 'color_number', 'packing')},
            },
        ),
    ]
