# Generated by Django 3.2.9 on 2022-03-31 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gellifihouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missgelproducts',
            name='gellifique_ean13',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='missgelproducts',
            name='gellifique_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='missgelproducts',
            name='gellifique_old_ean13',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='missgelproducts',
            name='gellifique_old_names',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
