# Generated by Django 3.2.9 on 2022-03-31 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gellifihouse', '0002_auto_20220331_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='missgelproducts',
            name='gellifique_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='missgelproducts',
            name='gellifique_old_ids',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
