# Generated by Django 3.2.9 on 2022-03-31 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gellifihouse', '0003_auto_20220331_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissGelOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Agreed'), (2, 'Paid'), (3, 'Shipped'), (4, 'In Customs'), (5, 'Received')], default=0)),
                ('order_dt', models.DateField(blank=True, null=True)),
                ('received_dt', models.DateField(blank=True, null=True)),
                ('batch_code', models.CharField(blank=True, max_length=50, null=True)),
                ('gellifique_code', models.CharField(blank=True, max_length=50, null=True)),
                ('product_cost', models.FloatField(default=0)),
                ('discount', models.FloatField(default=0)),
                ('shipping', models.FloatField(default=0)),
                ('extra_cost1', models.FloatField(default=0)),
                ('extra_cost2', models.FloatField(default=0)),
                ('extra_cost3', models.FloatField(default=0)),
                ('total_cost', models.FloatField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
