# Generated by Django 3.2.9 on 2022-03-31 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gellifihouse', '0004_missgelorders'),
    ]

    operations = [
        migrations.AddField(
            model_name='missgelorders',
            name='doc',
            field=models.FileField(blank=True, null=True, upload_to='missgel/%Y/%m/%d/'),
        ),
    ]
