# Generated by Django 3.2.12 on 2022-04-02 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gellifihouse', '0005_missgelorders_doc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='missgelorders',
            options={'ordering': ['-name']},
        ),
        migrations.AlterModelOptions(
            name='missgelproducts',
            options={'ordering': ['name', 'color_number', 'packing']},
        ),
        migrations.CreateModel(
            name='MissGelOrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color_number', models.CharField(max_length=50)),
                ('packing', models.CharField(max_length=50)),
                ('gellifique_name', models.CharField(blank=True, max_length=50, null=True)),
                ('gellifique_ean13', models.CharField(blank=True, max_length=13, null=True)),
                ('gellifique_id', models.IntegerField(blank=True, null=True)),
                ('price', models.FloatField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('total_cost', models.FloatField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gellifihouse.missgelorders')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gellifihouse.missgelproducts')),
            ],
            options={
                'ordering': ['order', 'name'],
                'unique_together': {('order', 'name', 'color_number', 'packing')},
            },
        ),
    ]
