# Generated by Django 3.2.12 on 2022-05-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gellifihouse', '0006_auto_20220402_1529'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='missgelorderdetail',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='missgelorderdetail',
            name='notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='missgelproducts',
            name='notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
