# Generated by Django 3.2.12 on 2022-05-13 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gellifihouse', '0007_auto_20220513_1614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='missgelorderdetail',
            options={'ordering': ['order', 'name']},
        ),
    ]
