# Generated by Django 3.2.12 on 2022-05-13 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gellifihouse', '0008_alter_missgelorderdetail_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='missgelorderdetail',
            options={'ordering': ['order', 'id']},
        ),
        migrations.CreateModel(
            name='ShopAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('quantity_left', models.IntegerField(default=0)),
                ('quantity_just_added', models.IntegerField(default=0)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('updated_dt', models.DateTimeField(auto_now=True)),
                ('order_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gellifihouse.missgelorderdetail')),
            ],
        ),
    ]
