# Generated by Django 3.2.12 on 2022-05-13 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gellifihouse', '0009_auto_20220513_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopallocation',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gellifihouse.missgelorders'),
        ),
    ]
