# Generated by Django 3.2.12 on 2022-05-13 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gellifihouse', '0010_shopallocation_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopallocation',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gellifihouse.missgelorders'),
        ),
    ]
