# Generated by Django 3.2.12 on 2022-05-13 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gellifihouse', '0011_alter_shopallocation_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopallocation',
            name='gellifique_ean13',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='shopallocation',
            name='gellifique_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
