# Generated by Django 3.2.12 on 2022-08-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20220331_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='email_subject',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Subject'),
        ),
    ]
