# Generated by Django 3.2.20 on 2023-08-21 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='email_subsubject',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Sub-Subject'),
        ),
    ]
