# Generated by Django 3.2.20 on 2023-08-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_categorylang'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlang',
            name='email_subsubject',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Sub-Subject'),
        ),
    ]
