# Generated by Django 3.2.22 on 2023-12-06 14:48

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_postlang_email_subsubject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlang',
            name='text',
            field=markdownx.models.MarkdownxField(blank=True, verbose_name='Text'),
        ),
    ]
