# Generated by Django 3.2.22 on 2023-12-21 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_postlang_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False, verbose_name='Draft'),
        ),
        migrations.AddField(
            model_name='post',
            name='page',
            field=models.BooleanField(default=False, verbose_name='Publish as page'),
        ),
    ]
