# Generated by Django 3.2.22 on 2023-12-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20231221_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='planned_dt',
            field=models.DateField(blank=True, null=True, verbose_name='Planned'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='blog.Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=True, verbose_name='Draft'),
        ),
    ]
