# Generated by Django 3.2.12 on 2022-05-30 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(default='-', max_length=100, verbose_name='customer_name')),
                ('customer_email', models.CharField(default='-', max_length=100, verbose_name='customer_email')),
                ('created_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created_dt')),
                ('updated_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='created_dt')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='subtotal')),
                ('discount_pc', models.IntegerField(choices=[(0, '0'), (10, '10%'), (20, '20%'), (30, '30%'), (40, '40%'), (50, '50%')], default=20, verbose_name='discount_pc')),
                ('discount_gbp', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='discount_gbp')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='total')),
                ('status', models.IntegerField(choices=[(0, 'New'), (1, 'Paid'), (-1, 'Cancelled'), (-2, 'Refunded')], default=0, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('reference', models.CharField(max_length=100, verbose_name='reference')),
                ('name', models.CharField(max_length=500, verbose_name='name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='price')),
                ('ean13', models.TextField(blank=True, default='', verbose_name='ean13')),
                ('quantity', models.IntegerField(default=0, verbose_name='quantity')),
            ],
            options={
                'ordering': ['reference'],
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='quantity')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderdetail_set', to='pos.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pos.product')),
            ],
        ),
    ]
