# Generated by Django 3.2.12 on 2022-06-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('GellifiQue', 'GellifiQue'), ('Siberica', 'Siberica'), ('Staleks', 'Staleks')], default='GellifiQue', max_length=50, verbose_name='brand'),
        ),
    ]
