# Generated by Django 3.2.12 on 2022-06-10 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_auto_20220610_1826'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['brand', 'name']},
        ),
    ]
