# Generated by Django 3.2.12 on 2022-06-11 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_orderdetail_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='price',
        ),
    ]
