# Generated by Django 3.2.22 on 2023-12-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestashop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_product', models.PositiveIntegerField()),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('created_by', models.PositiveIntegerField()),
            ],
        ),
    ]
