# Generated by Django 3.2.22 on 2023-12-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestashop', '0002_productnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productnote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
