# Generated by Django 3.2.22 on 2024-01-30 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestashop', '0003_alter_productnote_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='productnote',
            name='domain',
            field=models.IntegerField(choices=[(1, 'Co Uk'), (2, 'Eu')], default=1),
        ),
    ]
