# Generated by Django 4.1.7 on 2024-05-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestashop', '0005_erroralert'),
    ]

    operations = [
        migrations.AddField(
            model_name='erroralert',
            name='error_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
