# Generated by Django 4.1.7 on 2024-12-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestashop', '0006_erroralert_error_dt'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_product', models.PositiveIntegerField()),
                ('inventory_type', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('domain', models.IntegerField(choices=[(1, 'Co Uk'), (2, 'Eu')], default=1)),
            ],
        ),
    ]
