# Generated by Django 4.1.7 on 2023-04-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dhlparcel',
            name='id_order',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
